[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
[project]
name = "MatplotLibAPI"
version="v3.0.5"
readme = "README.md"
requires-python=">=3.7"
dependencies = ["pandas","matplotlib","networkx","seaborn","scikit-learn",]


