[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
[project]
name = "MatplotLibAPI"
version = "v3.2.13"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "matplotlib",
    "networkx",
    "plotly",
    "seaborn",
    "scikit-learn",
    "kaleido",
    "nbformat",
    "numpy",
]
